### ISSUE TITLE
Reset filters button not working 

### ISSUE THREAD

**Issue by onos1** [namlit/siteswap_generator#29]
#### Expected behavior
After the clicking on the `reset filters` options, I expected everything to go back to default mode. 

#### Actual behavior
After clicking multiple times, the feature is not responding which means it's not working 

#### How to reproduce
- download site swap generator  [here](https://play.google.com/store/apps/details?id=namlit.siteswapgenerator)
- launch the app 
- change any default figures or clear all field 
- click the `reset filters` feature below 
Feature not responding. 

* Mobile : Infinix note 4
* Operating system: android 7.0
* Version : 1.0

#### Recording Of The Bug
https://youtu.be/LhCKbdX9AF8

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@onos/reset-filters-button-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by namlit** [comment]
Hi, the "reset filter" button was actually only intended to reset the custom filters and not the input fields. If you add any custom filters and than press the reset filter button, your custom filters get removed as intended.

Generally it might be an option to add a "reset input fields" button. However, I don't really want to combine that with the "reset filter" button, because after trying some filters, you often want to reset the filters, without changing the period length or number of objects. Personally I never had a need for resetting everything.

Does the App actually crash on you phone? From the video it looks like you are just pressing the "reset filter button" repeatedly. As the filters are already reset, of course nothing happens. Then you accidentally hit the "Generate Siteswaps" button. That is why you get the "Invalid Input Value" toast (Of course your input is invalid, as you have no input.). In the end it seems, that you just pull down the status bar, but the App is not crashing.
